### ISSUE TITLE
Get all rows

### ISSUE THREAD

**Issue by alexandrepossebom** [Evertras/bubble-table#10]
First of all, thanks for your amazing lib.

I need to get all rows to update data, please add a function to retrieve all rows or a function to clear the table rows and add new ones.

If you have solution for this please let me know.

Thank you in advanced

**Comment by Evertras** [comment]
Hey there, thanks for taking a look!

I would be careful not to treat the table as a data store, and instead treat it as a one way operation; it should create data rows from some data source, and not be the data source itself.  There's already a way to reapply new data, so I've added [this example](https://github.com/Evertras/bubble-table/tree/main/examples/updates) to show rapidly updating table rows.  Would this fit your use case?  If not I'm happy to explore other options.

**Comment by alexandrepossebom** [comment]
I'll take a look at this and then come back with feedback if it worked.

Thank you very much

**Comment by alexandrepossebom** [comment]
@Evertras  thank you very much, it's exactly what I need!
