### ISSUE TITLE
How can I format numbers in a sortable column?

### ISSUE THREAD

**Issue by DiabeticOwl** [Evertras/bubble-table#126]
Greetings, I would like to know how to display a column's values in a specific format.

I have been working with a [project](https://github.com/DiabeticOwl/htop-clone/tree/htop-clone-UI) in which I use bubble-table as the main UI. On one of my displayed tables I sort its rows by a float based column which I desire to display in the `"%.4f%%"` format. The current version treats the values as strings, disrupting the order while sorting the column.

I have succeeded by doing the following:
    * modifying the asNumber function in the [data.go](https://github.com/Evertras/bubble-table/blob/main/table/data.go#L49) file in order to replace the "%" on passed values of type string and then casting them into floats
    * giving an extra field of type string to the StyledCell type in the cell.go file. When the switch statement in renderRowColumnData from the [row.go](https://github.com/Evertras/bubble-table/blob/main/table/row.go#L75) file catches the described type, its new field will be used instead of the default `"%v"`.

Despite both approaches working, I'd rather not adjust upstream libraries. Is there a way to do this with the framework as is?

**Comment by Evertras** [comment]
This is not currently possible, but this is something that I think should be implemented.  I'll add a numeric format string to the column, which should allow you to do what you're asking here without having to inject anything strange.

**Comment by Evertras** [comment]
I've added the option to columns in `v0.14.6`.  The [sorting example](https://github.com/Evertras/bubble-table/tree/main/examples/sorting) has been updated with your use case in mind.  Let me know if this covers what you want to do, or if you think there needs to be any other changes.

**Comment by DiabeticOwl** [comment]
It does cover what I want to do, thank you!
