### ISSUE TITLE
Test failure: Test3xWithFilterFooter

### ISSUE THREAD

**Issue by major** [Evertras/bubble-table#150]
I'm working to package bubble-table in Fedora Linux, but I keep stumbling into a failing test:

```
--- FAIL: Test3x3WithFilterFooter (0.00s)
    view_test.go:707: 
        	Error Trace:	/builddir/build/BUILD/bubble-table-4cda4a722c380a39ec64db9f7adb7178ddf32d47/_build/src/github.com/evertras/bubble-table/table/view_test.go:707
        	Error:      	Not equal: 
        	           	expected: "┏━━━━┳━━━━┳━━━━┓\n┃   1┃   2┃   3┃\n┣━━━━╋━━━━╋━━━━┫\n┃ 1,3┃ 2,3┃ 3,3┃\n┣━━━━┻━━━━┻━━━━┫\n┃           /3\x1b[7m \x1b[0m┃\n┗━━━━━━━━━━━━━━┛"
        	           	actual  : "┏━━━━┳━━━━┳━━━━┓\n┃   1┃   2┃   3┃\n┣━━━━╋━━━━╋━━━━┫\n┃ 1,3┃ 2,3┃ 3,3┃\n┣━━━━┻━━━━┻━━━━┫\n┃            /3┃\n┗━━━━━━━━━━━━━━┛"
        	           	
        	           	Diff:
        	           	--- Expected
        	           	+++ Actual
        	           	@@ -5,3 +5,3 @@
        	           	┣━━━━┻━━━━┻━━━━┫
        	           	-┃           /3 ┃
        	           	+┃            /3┃
        	           	┗━━━━━━━━━━━━━━┛
        	Test:       	Test3x3WithFilterFooter
FAIL
exit status 1
FAIL	github.com/evertras/bubble-table/table	0.021s
```

I get this failure with the latest release 0.15.2 as well as the latest commit in the main branch. This is with Go 1.20.5.

**Comment by Evertras** [comment]
Hey there, sorry for being a bit late to respond.  Before seeing this issue I was actually unaware that you could package Go libraries like this, so I may need a little more info to reproduce this.  If I set up a Fedora instance and just run `make test` would I see this error?  Do you think I could reproduce this in a Fedora docker image, or a VM?

Also to confirm, are you able to make this test pass in a regular dev environment outside Fedora?  I'd like to narrow down the actual environment this is happening in as much as possible.

**Comment by Evertras** [comment]
As a followup, I have a bit of time now so I tried spinning up a Fedora docker container with go 1.20.5 on it, and was able to get the tests to pass without issue, so there doesn't seem anything inherently different about Fedora itself.  I suspect there's something about the build process which is confusing the terminal output somewhere, and will need a bit more info about how that process is running to reproduce this.

**Comment by major** [comment]
Thanks for the replies! I have this on my to-do list but my list has grown a bit long for the week. :cry:

**Comment by Evertras** [comment]
I'm going to close this for now just to clean up, but please feel free to reopen if you get this reproducible.
