### ISSUE TITLE
Dynamically adding rows to table 

### ISSUE THREAD

**Issue by 3goats** [Evertras/bubble-table#156]
Hi, this is very useful thanks for all of the work. 

I'm looking at the `features` example and wondering how I can dynamically add rows to the table. I have some basic Bubbletea demos working where I'm using something like `p.send(struct{})` to add items to a list. Is this supported in the features example ? Could you provide a simple example ?

**Comment by Evertras** [comment]
Hey there, glad it's helpful!

The general idea is that you don't programmatically "add" or "remove" data from the table, you provide a single full view each time the view updates.  If you want to add data, you would add those items to an internal list that you keep yourself and then update the table by sending it a message with the updated data.

The best example of this would be [the update example](https://github.com/Evertras/bubble-table/tree/main/examples/updates), which pretends an API is sending new data on some timer.  The idea is that once new data is sent as a message, we see that [here](https://github.com/Evertras/bubble-table/blob/main/examples/updates/main.go#L104) and update the table state.  In the case of the example, it then starts a timer to update data [here](https://github.com/Evertras/bubble-table/blob/main/examples/updates/main.go#L118-L123), but in your case some other trigger would be sending the updated list of data.

Hopefully that makes sense.  Let me know if I can explain further.

**Comment by 3goats** [comment]
Thanks for the reply here. This all makes sense and I'll try it today.

**Comment by Evertras** [comment]
I'm going to close this for now to keep things tidy, but please feel free to reopen this or open a new issue if you have any questions!
