### ISSUE TITLE
Private fields and no getters for table.Column

### ISSUE THREAD

**Issue by prgres** [Evertras/bubble-table#157]
Is there any specific reason why all fields are private/don't have getters? I would need to have access to the 'key' property and do not know if I should prepare a PR :)

**Comment by Evertras** [comment]
To clarify, you mean the key property of Column?

Everything is unexported to avoid any modifications that would break the flow of Bubble Tea; everything must be immutable.  I'm not against adding a read-only getter for Column.key in particular, if that would be useful to you.

**Comment by Evertras** [comment]
Got it... sounds good then, should be pretty straightforward!  I'll keep an eye out for PR.

**Comment by prgres** [comment]
https://github.com/Evertras/bubble-table/pull/158

**Comment by Evertras** [comment]
Released as [v0.15.5](https://github.com/Evertras/bubble-table/releases/tag/v0.15.5)
