### ISSUE TITLE
Selected items are cleared after regenerating rows using WithRows()

### ISSUE THREAD

**Issue by sho-87** [Evertras/bubble-table#167]
Creating a new issue for this problem mentioned here:

> Interestingly, I'm also realizing now that the select functionality won't persist after `WithRows` is called, because it doesn't know which new row corresponds to an old selected row. 
> That may need some further thought, and if you need this functionality let's open a new issue.  This issue will just be scoped to fixing the disappearing column, I just wanted to point that out as a potential followup.

_Originally posted by @Evertras in https://github.com/Evertras/bubble-table/issues/163#issuecomment-1962895300_

I actually had a TODO note in my project to see what was going on with this as I thought it was a problem with my code.

I had a temporary fix by using a function to just match up a certain column value (eg a name column) between the pre and post table rows and reselect programmatically after running WithRows, but this very quickly runs into issues if you have duplicates values in a column. Also thought about running a SHA over the values of a row to generate unique IDs and match rows up by that ID. neither approach is that elegant...

**Comment by sho-87** [comment]
> Basically, insist that the rows contain some unique ID, and reapply the selection whenever new rows are given? 🤔

this is probably the simplest solution, although I would maybe let the user enter as many columns as they want instead of just one. basically to create a compound key on the fly as it loosens the requirement that any one column must be unique

the only situation this wouldnt cover is one where all row values change but is still considered the same row entry e.g. each table row represents a project but I want to change all the values associated with that project. this might be too niche of a use case, and I imagine it would require a more fundamental redesign of the row mechanic to be able to handle

> Another potential solution would be to provide a user-specified function that tests two rows for "equality", which would be more painful to use but provide more flexibility.

I think if I get to the point where Id need to write my own equality function I may as well write my own function to handle the entire reselection myself. that would at least give me unlimited flexibility and can be tailored to exactly what I need

> Additionally there's an interesting scenario to think through about reappearing rows. Let's say you have a row with some column ID of X, and you're persisting selections with that column. You do `WithRows` and that row X is not in the new set. Then you do `WithRows` and provide a set of rows that once again includes X. Should X be selecterd?

I imagine this could go either way depending on specifically what the user wants to do with the table. the combination of `PersistSelectableOnColumns()` and `PersistSelectableUntilRemoved(bool)` would provide enough option flexibility to handle most of these cases

**Comment by Evertras** [comment]
> this is probably the simplest solution, although I would maybe let the user enter as many columns as they want instead of just one. basically to create a compound key on the fly as it loosens the requirement that any one column must be unique

I generally agree, but I'm curious how far this rabbit hole may go.  As in, are there other use cases that may benefit from having a persisting "id" across rows?  Then maybe it's worth creating a more generic "WithRowIDKeys" or similar, because if we add this and then need it elsewhere it's going to get quite messy.  But if we only ever use it for this, then it's not very clear how to use it or why you would want to use it.  Hmm.

I think this will still actually cover the case where row values change as long as a hidden ID can be supplied with the project in your example.  The key doesn't necessarily need to be visible in the table.

Will consider this a bit more.  Slow for the moment due to other obligations, but I think it's still worth tackling this.

**Comment by Evertras** [comment]
Given https://github.com/Evertras/bubble-table/pull/171 would this be fixed now?  I added an internal ID to each row and how selections were being made.

**Comment by sho-87** [comment]
nice, thank you!
