### ISSUE TITLE
Clearing filter after selecting a row

### ISSUE THREAD

**Issue by TuanSSM** [Evertras/bubble-table#170]
Hello, first of all thanks for your efforts on this project.

After applying a filter to the table and selecting a row, if I clear the filter, the table does not revert to its initial state with selections.

![Before filtering](https://github.com/Evertras/bubble-table/assets/6631289/cb8ec774-75ac-4f04-a782-4088b893d7f7)

![Selection with filter](https://github.com/Evertras/bubble-table/assets/6631289/3aea2494-a9db-4837-89d5-a29288137173)

![Filter cleared](https://github.com/Evertras/bubble-table/assets/6631289/2d04cb15-c588-41cf-baf7-af01c2e990f7)

**Comment by Evertras** [comment]
Just reproduced, definitely an interesting bug.  I think it's because of how the rows are replaced internally during some operations... I'll take a look into this, this needs to be fixed.

**Comment by Evertras** [comment]
This should be fixed now.  I redid how we update the selection toggle, which has the added benefit of also being faster than the old way, so hopefully this is a win/win for everyone.  Thanks for the report!

Try v0.15.8 and feel free to close if that fixes it, or let me know if there's anything still broken.

**Comment by TuanSSM** [comment]
Works flawless, thank you for quick fix 👑
