### ISSUE TITLE
examples/scrolling UI is broken

### ISSUE THREAD

**Issue by 766b** [Evertras/bubble-table#181]
![image](https://github.com/user-attachments/assets/3e4b88c5-976d-4997-a7fe-c53241c83418)

Scrolling example border seems to be broken.

```
github.com/charmbracelet/bubbletea v0.27.1
github.com/charmbracelet/lipgloss v0.13.0
go version go1.23.0 windows/amd64
```

**Comment by Evertras** [comment]
Thanks for the fix!
