### ISSUE TITLE
Style by cell

### ISSUE THREAD

**Issue by alexandrepossebom** [Evertras/bubble-table#19]
Will be great if I can set style by cell

**Comment by Evertras** [comment]
I thought this would be possible by applying the style directly to the entry, but that actually breaks everything.  I'll look into supporting this shortly.

**Comment by alexandrepossebom** [comment]
thank you a lot!

**Comment by Evertras** [comment]
Added, please check the updated feature example and the readme for samples.  Let me know if there's anything else that needs to be added, or feel free to close the issue if not.  Accidentally closed automatically.

**Comment by alexandrepossebom** [comment]
It's exactly what I need! Thanks
