### ISSUE TITLE
Go to Start/End Keys for Paginator

### ISSUE THREAD

**Issue by astrogewgaw** [Evertras/bubble-table#30]
<div align="justify">

This is just a simple feature request: I think it will be nice if we have "Go to Start" and "Go to End" key bindings for the paginator, mapped to the `Home` and `End` keys. I think the implementation should be simple, but I was a bit unsure of how to add the functionality myself, so I did not go ahead with a PR. I thought this might be something on your mind as well, so I opened up an an issue instead.

**PS**: Great work on this project btw 😁 ! Thanks to this I did not have to go to all the trouble to try and come up with a table widget myself. The speed at which you are implementing all these features is almost unreal 😮 ! I started using it when you implemented pagination, which was a feature I sorely needed (the data I wanted to display had more than 3000 entries!).

</div>

**Comment by Evertras** [comment]
Hey there, glad you find it useful!

I'll add that in the near future, I just want to sort out #29 before coding anything as I think there will be some collisions.

Out of curiosity, how is the performance for you with 3000 entries?  Let me know if it's sluggish, I've prioritized correctness/simplicity over performance so far as I hadn't expected it to be used for that much!

**Comment by astrogewgaw** [comment]
<div align="justify">

Thanks for the quick reply 😁 ! I am seeing pretty good performance with 3000 entries so far. There were some lags before but they were because of how I was interacting with the SQL database, not because of the UI. Let me see if I can add some GIFs to my project's README. If you want to check it out yourself, the project is [**here**](https://github.com/astrogewgaw/koshka).

**PS**: Excited to see how **#29** unfolds.

</div>

**Comment by Evertras** [comment]
This should now be implemented in 0.7.0, give it a try and let me know if this works for you!  If so feel free to close the issue.
