### ISSUE TITLE
Customize Border Style

### ISSUE THREAD

**Issue by astrogewgaw** [Evertras/bubble-table#31]
<div align="justify">

Currently you can customize the style of the rows and columns, but I was unsure how to customize the border style. I know that you can customize the glyphs used for the border itself, but I just wanted to customize the foreground and background colors for the border. Is that something that you are thinking of implementing, or can it be done via some method that I don't know of? Right now I am wrapping the whole table in a `lipgloss.Style`, but some of the inner borders stay at the default color, rather than the one that I specified in the style. Maybe it will work if implemented here instead 🤔 ?

</div>

**Comment by Evertras** [comment]
#32 should take care of this, this was just an oversight on my part.  Now you can add `StyleBase` with something like `StyleBase: lipgloss.NewStyle().BorderForeground(lipgloss.Color("#a38")),`

I've added this to the main feature example.  Let me know if this does what you need and I'll do a release.

**Comment by astrogewgaw** [comment]
<div align="justify">

Good to know that you have already taken care of this.  I will give it a try and let you know if I run into any trouble 😁 ! And again, thanks for all the good work you have done here 👍🏾 !

</div>

**Comment by Evertras** [comment]
Great, give v0.6.2 a shot and let me know!  If it works for you, feel free to close the issue after confirming.

**Comment by astrogewgaw** [comment]
<div align="justify">

Just did, and it is working like a charm 👍🏾 😁 ! I do have one little question though: right now it seems as if to change the border style you have to specify a custom `Border`, but there is no way to do that without specifying all the glyphs as well. Wouldn't it be better if one could change the glyphs and style independently? Maybe something like what `HeaderStyle` does?

</div>

**Comment by Evertras** [comment]
...good point, that should be a separately set option.

I'll leave the BaseStyle as it is for the border, but I'll also add a global base style.  This was almost part of #26 anyway, so it seems like it would be useful for borders as well as things like alignment, etc.

**Comment by astrogewgaw** [comment]
Sounds great 👍🏾 !

**Comment by Evertras** [comment]
Should be fixed by #34 and released as v0.6.3... I ended up taking out the border BaseStyle because it's very misleading with the new global style.  Going to take advantage of this being pre-1.0 and break things a bit. ;)

**Comment by Evertras** [comment]
Hey, just checking, can this be closed now?

**Comment by Evertras** [comment]
I'm going to close this for now as I think it's handled, but please feel free to reopen if you think something is missing!
