### ISSUE TITLE
Default borders misalign when using double width for ambiguous characters

### ISSUE THREAD

**Issue by bingoohuang** [Evertras/bubble-table#39]
Hi, I run your example and got the following result. It's mis-aligned, is there  anything setting i missed? what's your font family?

![image](https://user-images.githubusercontent.com/1940588/156978429-ca33beb9-6332-4b5d-b4a4-8991d47ad675.png)

**Comment by Evertras** [comment]
That looks very wrong, yes :(

I've tested this on the Alacritty and iTerm2 terminals, and I tried it with the Menlo, Input, and Azeret Mono fonts.  I have not seen output like your screenshot.  What terminal/font are you using?

**Comment by bingoohuang** [comment]
Mac, iterm2 Build 3.4.15, 

![image](https://user-images.githubusercontent.com/1940588/156994045-ffd34b21-00bc-45a3-ac7c-aa92044bb895.png)

I tried several monospace fonts, and can't get the aligned version as yours in README.

**Comment by Evertras** [comment]
I was able to reproduce this: it's the `Ambiguous characters are double-width` option.  Disabling that shows the proper layout.

I think it's the `─` character in particular.  There may be some other unicode characters that would work better here, but that character set was intended for box drawing so if this is broken then I'm not optimistic others will work.  I'll experiment more with this when I get some time.

**Comment by Evertras** [comment]
Do you mind if I rename this bug to `Default borders misalign when using double width for ambiguous characters` for clarity?

**Comment by Evertras** [comment]
https://github.com/mattn/go-runewidth/issues/14 may be related

**Comment by Evertras** [comment]
https://github.com/charmbracelet/lipgloss/issues/40 also may be related

**Comment by ghostsquad** [comment]
Disable `Ambiguous Characters are Double Width` and try setting `export RUNEWIDTH_EASTASIAN=0` environment variable before running.

**Comment by bingoohuang** [comment]
![image](https://user-images.githubusercontent.com/1940588/170853739-d3484bcf-05ac-4ea0-b3d3-e0af6f240f8c.png)
