### ISSUE TITLE
Static footer cannot keep up with flex table.

### ISSUE THREAD

**Issue by astrogewgaw** [Evertras/bubble-table#48]
<div align="justify">

I just started using the latest release, and tried out the new flex table. I had a custom static footer in my app, inspired by one of your examples. Turns out, the footer cannot keep up with the width of the flex table. I guess that, somewhere in the code, the width of the static footer is not being updated, causing the issue. This makes the entire thing look a bit awkward:

![bug](https://user-images.githubusercontent.com/51956960/157275814-cd0b6c62-5872-4cea-ac7f-871e907866aa.png)

Let me know if I missed something.

**PS**: Thanks for all the new features 😁 ! All the contributors are doing some great work here 👍🏾 .

</div>

**Comment by Evertras** [comment]
Oh hmm, that definitely starts acting strangely in the flex-example when I try it as well.  It seems to be kind of lagging behind.  Let me poke at this, I have some suspicions of what might be wrong.

**Comment by astrogewgaw** [comment]
Just gave it a go, and looks like it is fixed 👍🏾 ! Thanks for the super fast response 😁 !
