### ISSUE TITLE
Search filters

### ISSUE THREAD

**Issue by Evertras** [Evertras/bubble-table#5]
We should be able to apply a search filter on a column and only display results that fit the filter.  Probably just a simple substring match to start.

**Comment by alswl** [comment]
Watching this repo, any progress? Is pull request is welcome?

**Comment by Evertras** [comment]
Hey there, I haven't had a chance to work on this issue yet.  Pull request is welcome for this one!

**Comment by Evertras** [comment]
@alswl I've implemented sorting which may have some overlap in terms of dealing iwth string values and nested StyledColumn values as part of #27 , but it's all mostly in new files so hopefully it doesn't collide too much if you've started work on this.  Let me know.

**Comment by alswl** [comment]
@Evertras I haven't started yet.

**Comment by Evertras** [comment]
Will close this after I bump the coverage back up 🎊
