### ISSUE TITLE
when filter rows, all rows should re-paginated

### ISSUE THREAD

**Issue by alswl** [Evertras/bubble-table#54]
When filter rows, all rows should re-paginated. 

Current situation: pagination data is still all rows, so if there is no matched rows in first page, it will be empty. But in the second page, data will be shown.

Wanted: When filtering, rows is paginated by filtered data, and the pagination info will be combined with two part (current num, and total num).

**Comment by alswl** [comment]
@Evertras Please confirm this case, I will focus on it if you think this is OK.

**Comment by Evertras** [comment]
> Current situation: pagination data is still all columns, so if there is no matched columns in first page, it will be empty. But in the second page, data will be shown.

To clarify, do you mean "all rows"?

I generally get the idea that pagination needs to be better updated when filters are applied, and that sounds like a reasonable thing to focus on!

**Comment by alswl** [comment]
@Evertras Yes, "rows", sorry for the low-level errors.
