### ISSUE TITLE
How to set page programmatically?

### ISSUE THREAD

**Issue by Robert-M-Muench** [Evertras/bubble-table#55]
How can I switch to a specific page programmatically when pagination is used?

The 'pageFirst()' is not public.

However, when
1. I load data into the table
2. the user navigates forward/backward
3. and I load new data

The table shows the current page, which might not exist because the new data is shorter.

'WithRows' doesn't reset the tables state, and there is no function to reset the tables' state.

**Comment by Evertras** [comment]
Hello, I've implemented a fix for the problem as described above by automatically bounding the page to a valid number when `WithRows` is used.  I think programmatically setting the page number will also be useful, let me think a bit about if there's any potential gotchas.

**Comment by Evertras** [comment]
Check `v0.8.5` release for the above fix

**Comment by Evertras** [comment]
I've added various pagination controls as well in `v0.9.0`.  If these changes are enough, please feel free to close the issue, or if there's something missing or working incorrectly please let me know!

**Comment by Evertras** [comment]
Hey there, just checking if this solved the issue?  If there's no response within a few days I'll close this just for tidiness, but if you come back and think it's not closed you're welcome to reopen it.
