### ISSUE TITLE
How to dynamically change header?

### ISSUE THREAD

**Issue by Robert-M-Muench** [Evertras/bubble-table#59]
How can I show an indicator for the column used for sorting?

The column.title is not accessible, and there is no function to alter it.

**Comment by Evertras** [comment]
Currently that isn't possible but this is definitely a reasonable thing to want to do.  This will need to be added.

**Comment by Evertras** [comment]
Please try the `v0.10.0` release with `WithColumns`, using [something similar to this example](https://github.com/Evertras/bubble-table/blob/main/examples/updates/main.go#L56) to generate the columns with their header text on the fly.

If this fixes the issue, please feel free to close it.  If it doesn't, please let me know if there's anything else that's required!

**Comment by Robert-M-Muench** [comment]
Yes, this works.

One thing: The only way to create a table is `table.New([]Column)`, when using `WithColumns` the `[]Column` is superfluous. Since Go doesn't allow overloading, maybe two separate names, or a generic config struct, allow `nil` might be better.
