### ISSUE TITLE
Support set the page size dynamic

### ISSUE THREAD

**Issue by alswl** [Evertras/bubble-table#69]
Reason: In common TUI projects, Terminal height is allowed to change. This allows auto-adapting in a full-screen mode (e.g. top command).

Current Status: The page size can not be modified, and adjusting the pageSize during runtime cannot change the table height.

Expectation: Table can be adjust page size at runtime, or allow setting max height to table for calculate page size automatically.

**Comment by Evertras** [comment]
This should already be possible by using `WithPageSize`.  I've added this functionality to the `make example-pagination` example in the PR linked above, and fixed an issue that came up to keep the user within the max page bounds.

Does this fit your expectation, or is there another aspect that needs to be changed?

**Comment by alswl** [comment]
Okay, I will try to use `WithPageSize`.

I've been learning React recently and I'm just starting to understand component data flow management. Just realized that `table.Model` is a Pure Function component.

Thanks.
