### ISSUE TITLE
Index out of range panic when the highlighted row index is higher than the filtered row count

### ISSUE THREAD

**Issue by Robert-M-Muench** [Evertras/bubble-table#76]
I'm using `HighlightedRow()` from inside the `Update()` function to access the detailed row data.

However, when filtering the table, I manage to create a panic:
1. set Page size to 20
2. select record 19
3. filter the table to < 19 records => panic
 
Looks like the case, when the table size gets shorter because of filtering, and the highlighted row is out of sight, accessing it, leads to the crash.

```go
Caught panic:

runtime error: index out of range [3] with length 1

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel.func3()
	/Users/robby/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.20.0/tea.go:359 +0x95
panic({0x115faa0, 0xc003685ba8})
	/usr/local/go/src/runtime/panic.go:844 +0x258
github.com/evertras/bubble-table/table.Model.HighlightedRow({{0xc0035fda40, 0x4, 0x4}, {0xc003702000, 0x1a2, 0x220}, 0x1, {{{0xc00014e000, 0x2, 0x2}, ...}, ...}, ...})
	bubble-table/table/options.go:84 +0x16c
```

**Comment by Evertras** [comment]
This should be solved by #70, I've just put out a new release as `v0.11.2` which includes this change.  Try updating and let me know if this still occurs, I can't reproduce it any longer in the latest codebase.
