### ISSUE TITLE
Feature request: select rows programatically

### ISSUE THREAD

**Issue by inkel** [Evertras/bubble-table#79]
Hi! It's me again 😸 

I've been using this component for a project soon to be open sourced and it's been great so far 👏🏽 but I've found myself in the situation of missing how to select rows programmatically. It would be nice if there was a `Row.Selected(bool)` method or similar that would allow for marking the rows as selected before displaying them. Also methods on `Model` to select all/none could be very handy.

What do you think? I could try taking a stab at this in a PR.

**Comment by Evertras** [comment]
Hello, and welcome back! 🤘 

I think `Row.Selected(bool)` would be an easy win there and I'd be happy to accept a PR or that one.  I'm a little unsure initially how to approach the methods on Model, however, besides offering a way to select by index.  I'm not against adding that method as well if you'd like to take a shot at it, but if you have other thoughts of what a user could select on with `Model` I'm open to discussion.

**Comment by inkel** [comment]
Yes, I'm happy to give it a try. In fact, I've already something that it is working, but the code is a mess, so I'll make some adjustments and send a PR soon.

**Comment by inkel** [comment]
Hey! I've opened #84 for this, what do you think of moving the discussion there?

**Comment by Evertras** [comment]
Thanks for the PR!  I think we can decide here whether we want to add anything else to `Model` or not, but that PR is pretty nicely self-contained to add `Selected` to rows as discussed above.

**Comment by Evertras** [comment]
Is there anything else we want to do for this particular issue?  Otherwise I'd like to close it for tidiness.  If you want to discuss other options for `Model` methods and such I'm happy to.

**Comment by Evertras** [comment]
...that PR is the wrong issue link, sorry!

**Comment by inkel** [comment]
Heya! No, I don't think there's anything else. I've been using this locally and it's been working just fine, so it's ok to close.
